language: java
sudo: false
before_install:
- cd etc/build
script: ant war
before_deploy:
- cd $TRAVIS_BUILD_DIR
deploy:
  provider: releases
  api_key:
    secure: 3A/59GcxN/u5TfRgakStxJmAGBFrrAgxRyXUbD4PjOTioBSHsCLuf+68NCsfdZW2yxfO0MudwrhJE5E42CL31LBbHyk23e4IZ9fGnsRC2WrkyzZZnXsKqstaumIQDlt+E62e7qOy3x4a0k7kh9I0FiPZuXaVpL0sB35XfTz0W5aigcGGghJ+1DbnPpoG2qdi2BjzxpH+kAxcQA5l7QYv9aMjlguR7Sp8kuB4nNVZaqhQpY7ADTvx7FNiqKEWUYbXesRLoF+tzPgvQcJUXvRYsOVCjU/Xj81njrHlVYxv+JsX4wMdQt7XMDXF8NdugbxQHbl9Kmp2b+Q+EzN5WA9jph2+1k3HjnP3RtMlpEvHYAn3hMsk3nHHepy++GWUXq8oYM2UUJltPBUIdBjdoPyyDNvPVIvwP0a27wxv/k9BgIx4fUniZbt/fNaufv66x3Pz6QZvamq+vZePoUvLmxSUvzPABd9HPQoLwGSqLK17GzvMkSCofDz06OhVGs4/oIPdts9kZx5rX00Wil151LAOYPtYRX2861IGOmo/FTAsMM8th6sOGYUtL+CM19OfEXYX3NKP1yTlukG5922ExS6vo7Rs1WHcpR+xlpa6gFHo/znN/Skrmrzf6ojn/0O4jQgtEN5WSCPnSba25RTRGuE6ymRxMZKDorPXwQa9puXO8kw=
  file: build/draw.war
  skip_cleanup: true
  on:
    repo: cern-drawio/drawio
    tags: true